<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return [
    'gateway_direct_payment_url' => 'https://direct.tranzila.com/',

    'gateway_url' => 'https://secure5.tranzila.com',

    // Api, Token Flow
    'gateway_url_prefix_71u' => '/cgi-bin/tranzila71u.cgi',

    // Shekel || Dollar
    'gateway_url_prefix_31' => '/cgi-bin/tranzila31.cgi',

    // Multi Currency URL
    'gateway_url_prefix_36a' => '/cgi-bin/tranzila36a.cgi',

    // Handshake URL
    'gateway_url_prefix_71dt' => '/cgi-bin/tranzila71dt.cgi',

    'currencies' => [
        'ILS' => 1,
        'USD' => 2,
        'EUR' => 978,
        'GBP' => 826,
        'JPY' => 392,
        'default' => 1
    ],

    'payment_types' => [
        'normal' => 1,
        'credit' => 6,
        'payments' => 8
    ],

    'languages' => [
        'default' => 'us',
        'he_IL' => 'il',
        'en_US' => 'us',
        'ru_RU' => 'ru',
        'es_ES' => 'es',
        'de_DE' => 'de',
        'fr_FR' => 'fr',
        'ja' => 'jp'
    ],

    'status_codes' => [
        '000' => __('Transaction approved', 'woocommerce-il-payment-gateways'),
        '001' => __('Blocked confiscate card.', 'woocommerce-il-payment-gateways'),
        '002' => __('Stolen confiscate card.', 'woocommerce-il-payment-gateways'),
        '003' => __('Contact credit company.', 'woocommerce-il-payment-gateways'),
        '004' => __('Refusal.', 'woocommerce-il-payment-gateways'),
        '005' => __('Forged. confiscate card.', 'woocommerce-il-payment-gateways'),
        '006' => __('Identity Number of CVV incorrect.', 'woocommerce-il-payment-gateways'),
        '007' => __('Must contact Credit Card Company', 'woocommerce-il-payment-gateways'),
        '008' => __('Fault in building of access key to blocked cards file.', 'woocommerce-il-payment-gateways'),
        '009' => __('Contact unsuccessful.', 'woocommerce-il-payment-gateways'),
        '010' => __('Program ceased by user instruction (ESC).', 'woocommerce-il-payment-gateways'),
        '011' => __('No confirmation for the ISO currency clearing.', 'woocommerce-il-payment-gateways'),
        '012' => __('No confirmation for the ISO currency type.', 'woocommerce-il-payment-gateways'),
        '013' => __('No confirmation for charge/discharge transaction.', 'woocommerce-il-payment-gateways'),
        '014' => __('Unsupported card', 'woocommerce-il-payment-gateways'),
        '015' => __('Number Entered and Magnetic Strip do not match', 'woocommerce-il-payment-gateways'),
        '017' => __('Last 4 digets not entered', 'woocommerce-il-payment-gateways'),
        '019' => __('Record in INT_IN shorter than 16 characters.', 'woocommerce-il-payment-gateways'),
        '020' => __('Input file (INT_IN) does not exist.', 'woocommerce-il-payment-gateways'),
        '021' => __('Blocked cards file (NEG) non-existent or has not been updated - execute transmission or request authorization for each transaction.', 'woocommerce-il-payment-gateways'),
        '022' => __('One of the parameter files or vectors do not exist.', 'woocommerce-il-payment-gateways'),
        '023' => __('Date file (DATA) does not exist.', 'woocommerce-il-payment-gateways'),
        '024' => __('Format file (START) does not exist.', 'woocommerce-il-payment-gateways'),
        '025' => __('Difference in days in input of blocked cards is too large - execute transmission or request authorization for each transaction.', 'woocommerce-il-payment-gateways'),
        '026' => __('Difference in generations in input of blocked cards is too large - execute transmission or request authorization for each transaction.', 'woocommerce-il-payment-gateways'),
        '027' => __('Where the magnetic strip is not completely entered', 'woocommerce-il-payment-gateways'),
        '028' => __('Central terminal number not entered into terminal defined for work as main supplier.', 'woocommerce-il-payment-gateways'),
        '029' => __('Beneficiary number not entered into terminal defined as main beneficiary.', 'woocommerce-il-payment-gateways'),
        '030' => __('Terminal not updated as main supplier/beneficiary and supplier/beneficiary number entered.', 'woocommerce-il-payment-gateways'),
        '031' => __('Terminal updated as main supplier and beneficiary number entered', 'woocommerce-il-payment-gateways'),
        '032' => __('Old transactions - carry out transmission or request authorization for each transaction.', 'woocommerce-il-payment-gateways'),
        '033' => __('Defective card', 'woocommerce-il-payment-gateways'),
        '034' => __('Card not permitted for this terminal or no authorization for this type of transaction.', 'woocommerce-il-payment-gateways'),
        '035' => __('Card not permitted for transaction or type of credit.', 'woocommerce-il-payment-gateways'),
        '036' => __('Expired.', 'woocommerce-il-payment-gateways'),
        '037' => __('Error in instalments - Amount of transaction needs to be equal to the first instalment + (fixed instalments times no. of instalments)', 'woocommerce-il-payment-gateways'),
        '038' => __('Cannot execute transaction in excess of credit card ceiling for immediate debit.', 'woocommerce-il-payment-gateways'),
        '039' => __('Control number incorrect.', 'woocommerce-il-payment-gateways'),
        '040' => __('Terminal defined as main beneficiary and supplier number entered.', 'woocommerce-il-payment-gateways'),
        '041' => __('Exceeds ceiling where input file contains J1 or J2 or J3 (contact prohibited).', 'woocommerce-il-payment-gateways'),
        '042' => __('Card blocked for supplier where input file contains J1 or J2 or J3 (contact prohibited).', 'woocommerce-il-payment-gateways'),
        '043' => __('Random where input file contains J1 (contact prohibited).', 'woocommerce-il-payment-gateways'),
        '044' => __('Terminal prohibited from requesting authorization without transaction (J5)', 'woocommerce-il-payment-gateways'),
        '045' => __('Terminal prohibited for supplier-initiated authorization request (J6)', 'woocommerce-il-payment-gateways'),
        '046' => __('Terminal must request authorization where input file contains J1 or J2 or J3 (contact prohibited).', 'woocommerce-il-payment-gateways'),
        '047' => __('Secret code must be entered where input file contains J1 or J2 or J3 (contact prohibited).', 'woocommerce-il-payment-gateways'),
        '051' => __(' Vehicle number defective.', 'woocommerce-il-payment-gateways'),
        '052' => __('Distance meter not entered.', 'woocommerce-il-payment-gateways'),
        '053' => __('Terminal not defined as gas station. (petrol card passed or incorrect transaction code).', 'woocommerce-il-payment-gateways'),
        '057' => __('Identity Number Not Entered', 'woocommerce-il-payment-gateways'),
        '058' => __('CVV2 Not Entered', 'woocommerce-il-payment-gateways'),
        '059' => __('Identiy Number and CVV2 Not Entered', 'woocommerce-il-payment-gateways'),
        '060' => __('ABS attachment not found at start of input data in memory.', 'woocommerce-il-payment-gateways'),
        '061' => __('Card number not found or found twice', 'woocommerce-il-payment-gateways'),
        '062' => __('Incorrect transaction type', 'woocommerce-il-payment-gateways'),
        '063' => __('Incorrect transaction code.', 'woocommerce-il-payment-gateways'),
        '064' => __('Type of credit incorrect.', 'woocommerce-il-payment-gateways'),
        '065' => __('Incorrect currency.', 'woocommerce-il-payment-gateways'),
        '066' => __('First instalment and/or fixed payment exists for non-instalments type of credit.', 'woocommerce-il-payment-gateways'),
        '067' => __('Number of instalments exists for type of credit not requiring this.', 'woocommerce-il-payment-gateways'),
        '068' => __('Linkage to dollar or index not possible for credit other than instalments.', 'woocommerce-il-payment-gateways'),
        '069' => __('Length of magnetic strip too short.', 'woocommerce-il-payment-gateways'),
        '070' => __('PIN terminal not defined', 'woocommerce-il-payment-gateways'),
        '071' => __('PIN must be enetered', 'woocommerce-il-payment-gateways'),
        '072' => __('Secret code not entered.', 'woocommerce-il-payment-gateways'),
        '073' => __('Incorrect secret code.', 'woocommerce-il-payment-gateways'),
        '074' => __('Incorrect secret code - last try.', 'woocommerce-il-payment-gateways'),
        '079' => __('Currency is not listed in vector 59.', 'woocommerce-il-payment-gateways'),
        '080' => __('"Club code" entered for unsuitable credit type', 'woocommerce-il-payment-gateways'),
        '090' => __('Transaction cancelling is not allowed for this card.', 'woocommerce-il-payment-gateways'),
        '091' => __('Transaction cancelling is not allowed for this card.', 'woocommerce-il-payment-gateways'),
        '092' => __('Transaction cancelling is not allowed for this card.', 'woocommerce-il-payment-gateways'),
        '099' => __('Cannot read/write/open TRAN file.', 'woocommerce-il-payment-gateways'),
        '100' => __('No equipment for inputting secret code.', 'woocommerce-il-payment-gateways'),
        '101' => __('No authorization from credit company for work.', 'woocommerce-il-payment-gateways'),
        '107' => __('Transaction amount too large - split into a number of transactions.', 'woocommerce-il-payment-gateways'),
        '108' => __('Terminal not authorized to execute forced actions.', 'woocommerce-il-payment-gateways'),
        '109' => __('Terminal not authorized for card with service code 587.', 'woocommerce-il-payment-gateways'),
        '110' => __('Terminal not authorized for immediate debit card.', 'woocommerce-il-payment-gateways'),
        '111' => __('Terminal not authorized for instalments transaction.', 'woocommerce-il-payment-gateways'),
        '112' => __('Terminal not authorized for telephone/signature only instalments transaction.', 'woocommerce-il-payment-gateways'),
        '113' => __('Terminal not authorized for telephone transaction.', 'woocommerce-il-payment-gateways'),
        '114' => __('Terminal not authorized for "signature only" transaction.', 'woocommerce-il-payment-gateways'),
        '115' => __('Terminal not authorized for dollar transaction.', 'woocommerce-il-payment-gateways'),
        '116' => __('Terminal not authorized for club transaction.', 'woocommerce-il-payment-gateways'),
        '117' => __('Terminal not authorized for stars/points/miles transaction.', 'woocommerce-il-payment-gateways'),
        '118' => __('Terminal not authorized for Isracredit credit.', 'woocommerce-il-payment-gateways'),
        '119' => __('Terminal not authorized for Amex Credit credit.', 'woocommerce-il-payment-gateways'),
        '120' => __('Terminal not authorized for dollar linkage.', 'woocommerce-il-payment-gateways'),
        '121' => __('Terminal not authorized for index linkage.', 'woocommerce-il-payment-gateways'),
        '122' => __('Terminal not authorized for index linkage with foreign cards.', 'woocommerce-il-payment-gateways'),
        '123' => __('Terminal not authorized for stars/points/miles transaction for this type of credit.', 'woocommerce-il-payment-gateways'),
        '124' => __('Terminal not authorized for Isracredit payments.', 'woocommerce-il-payment-gateways'),
        '125' => __('Terminal not authorized for Amex payments.', 'woocommerce-il-payment-gateways'),
        '126' => __('Terminal not authorized for this club code.', 'woocommerce-il-payment-gateways'),
        '127' => __('Terminal not authorized for immediate debit transaction except for immediate debit cards.', 'woocommerce-il-payment-gateways'),
        '128' => __('Terminal not authorized to accept Visa card staring with 3.', 'woocommerce-il-payment-gateways'),
        '129' => __('Terminal not authorized to execute credit transaction above the ceiling.', 'woocommerce-il-payment-gateways'),
        '130' => __('Card not permitted for execution of club transaction.', 'woocommerce-il-payment-gateways'),
        '131' => __('Card not permitted for execution stars/points/miles transaction.', 'woocommerce-il-payment-gateways'),
        '132' => __('Card not permitted for execution of dollar transactions (regular or telephone).', 'woocommerce-il-payment-gateways'),
        '133' => __('Card not valid according Isracard list of valid cards.', 'woocommerce-il-payment-gateways'),
        '134' => __('Defective card according to system definitions (Isracard VECTOR1) - no. of figures on card - error.', 'woocommerce-il-payment-gateways'),
        '135' => __('Card not permitted to execute dollar transactions according to system definition (Isracard VECTOR1).', 'woocommerce-il-payment-gateways'),
        '136' => __('Card belongs to group not permitted to execute transactions according to system definition (Visa VECTOR 20).', 'woocommerce-il-payment-gateways'),
        '137' => __('Card prefix (7 figures) invalid according to system definition (Diners VECTOR21)', 'woocommerce-il-payment-gateways'),
        '138' => __('Card not permitted to carry out instalments transaction according to Isracard list of valid cards.', 'woocommerce-il-payment-gateways'),
        '139' => __('Number of instalments too large according to Isracard list of valid cards.', 'woocommerce-il-payment-gateways'),
        '140' => __('Visa and Diners cards not permitted for club instalments transactions.', 'woocommerce-il-payment-gateways'),
        '141' => __('Series of cards not valid according to system definition (Isracard VECTOR5).', 'woocommerce-il-payment-gateways'),
        '142' => __('Invalid service code according to system definition (Isracard VECTOR6).', 'woocommerce-il-payment-gateways'),
        '143' => __('Card prefix (2 figures) invalid according to system definition (Isracard VECTOR7).', 'woocommerce-il-payment-gateways'),
        '144' => __('Invalid service code according to system definition (Visa VECTOR12).', 'woocommerce-il-payment-gateways'),
        '145' => __('Invalid service code according to system definition (Visa VECTOR13).', 'woocommerce-il-payment-gateways'),
        '146' => __('Immediate debit card prohibited for execution of credit transaction.', 'woocommerce-il-payment-gateways'),
        '147' => __('Card not permitted to execute instalments transaction according to Leumicard vector no. 31.', 'woocommerce-il-payment-gateways'),
        '148' => __('Card not permitted for telephone and signature only transaction according to Leumicard vector no. 31', 'woocommerce-il-payment-gateways'),
        '149' => __('Card not permitted for telephone transaction according to Leumicard vector no. 31', 'woocommerce-il-payment-gateways'),
        '150' => __('Credit not approved for immediate debit cards.', 'woocommerce-il-payment-gateways'),
        '151' => __('Credit not approved for foreign cards.', 'woocommerce-il-payment-gateways'),
        '152' => __('Club code incorrect.', 'woocommerce-il-payment-gateways'),
        '153' => __('Card not permitted to execute flexible credit transactions (Adif/30+) according to system definition (Diners VECTOR21).', 'woocommerce-il-payment-gateways'),
        '154' => __('Card not permitted to execute immediate debit transactions according to system definition (Diners VECTOR21).', 'woocommerce-il-payment-gateways'),
        '155' => __('Amount of payment for credit transaction too small.', 'woocommerce-il-payment-gateways'),
        '156' => __('Incorrect number of instalments for credit transaction', 'woocommerce-il-payment-gateways'),
        '157' => __('0 ceiling for this type of card for regular credit or Credit transaction.', 'woocommerce-il-payment-gateways'),
        '158' => __('0 ceiling for this type of card for immediate debit credit transaction', 'woocommerce-il-payment-gateways'),
        '159' => __('0 ceiling for this type of card for immediate debit in dollars.', 'woocommerce-il-payment-gateways'),
        '160' => __('0 ceiling for this type of card for telephone transaction.', 'woocommerce-il-payment-gateways'),
        '161' => __('0 ceiling for this type of card for credit transaction.', 'woocommerce-il-payment-gateways'),
        '162' => __('0 ceiling for this type of card for instalments transaction.', 'woocommerce-il-payment-gateways'),
        '163' => __('American Express card issued abroad not permitted for instalments transaction.', 'woocommerce-il-payment-gateways'),
        '164' => __('JCB cards permitted to carry out regular credit transactions.', 'woocommerce-il-payment-gateways'),
        '165' => __('Amount in stars/points/miles larger than transaction amount.', 'woocommerce-il-payment-gateways'),
        '166' => __('Club card not in terminal range.', 'woocommerce-il-payment-gateways'),
        '167' => __('Stars/points/miles transaction cannot be executed.', 'woocommerce-il-payment-gateways'),
        '168' => __('Dollar transaction cannot be executed for this type of card.', 'woocommerce-il-payment-gateways'),
        '169' => __('Credit transaction cannot be executed with other than regular credit.', 'woocommerce-il-payment-gateways'),
        '170' => __('Amount of discount on stars/points/miles greater than permitted.', 'woocommerce-il-payment-gateways'),
        '171' => __('Forced transaction cannot be executed with credit/immediate debut card.', 'woocommerce-il-payment-gateways'),
        '172' => __('Previous transaction cannot be cancelled (credit transaction or card number not identical).', 'woocommerce-il-payment-gateways'),
        '173' => __('Double transaction.', 'woocommerce-il-payment-gateways'),
        '174' => __('Terminal not permitted for index linkage for this type of credit.', 'woocommerce-il-payment-gateways'),
        '175' => __('Terminal not permitted for dollar linkage for this type of credit.', 'woocommerce-il-payment-gateways'),
        '176' => __('Card invalid according to system definition (Isracard VECTOR1)', 'woocommerce-il-payment-gateways'),
        '177' => __('Cannot execute "Self-Service" transaction at gas stations except at "Self-Service at gas stations".', 'woocommerce-il-payment-gateways'),
        '178' => __('Credit transaction forbidden with stars/points/miles.', 'woocommerce-il-payment-gateways'),
        '179' => __('Dollar credit transaction forbidden on tourist card.', 'woocommerce-il-payment-gateways'),
        '180' => __('Club Card can not preform Telephone Transactions', 'woocommerce-il-payment-gateways'),
        '200' => __('Application error.', 'woocommerce-il-payment-gateways'),
        '700' => __('Approved TEST Masav transaction', 'woocommerce-il-payment-gateways'),
        '701' => __('Invalid Bank Number', 'woocommerce-il-payment-gateways'),
        '702' => __('Invalid Branch Number', 'woocommerce-il-payment-gateways'),
        '703' => __('Invalid Account Number', 'woocommerce-il-payment-gateways'),
        '704' => __('Incorrect Bank/Branch/Account Combination', 'woocommerce-il-payment-gateways'),
        '705' => __('Application Error', 'woocommerce-il-payment-gateways'),
        '706' => __('Supplier directory does not exist', 'woocommerce-il-payment-gateways'),
        '707' => __('Supplier configuration does not exist', 'woocommerce-il-payment-gateways'),
        '708' => __('Charge amount zero or negative', 'woocommerce-il-payment-gateways'),
        '709' => __('Invalid configuration file', 'woocommerce-il-payment-gateways'),
        '710' => __('Invalid date format', 'woocommerce-il-payment-gateways'),
        '711' => __('DB Error', 'woocommerce-il-payment-gateways'),
        '712' => __('Required parameter is missing', 'woocommerce-il-payment-gateways'),
        '800' => __('Transaction Canceled', 'woocommerce-il-payment-gateways'),
        '900' => __('3D Secure Failed', 'woocommerce-il-payment-gateways'),
        '903' => __('Fraud suspected', 'woocommerce-il-payment-gateways'),
        '951' => __('Protocol Error', 'woocommerce-il-payment-gateways'),
        '952' => __('Payment not completed', 'woocommerce-il-payment-gateways'),
        '954' => __('Payment Failed', 'woocommerce-il-payment-gateways'),
        '955' => __('Payment status error', 'woocommerce-il-payment-gateways'),
        '959' => __('Payment completed unsuccessfully', 'woocommerce-il-payment-gateways'),
    ]
];